#target : Dependencies
#<TAB>commands

Build : project_main.c calender.c test_calender.c unity.c
	gcc project_main.c calender.c test_calender.c unity.c -o calender.out
Run : calender.out
	./calender.out
Clean :
	rm -rf *.o *.out *.i *.s 